baseURL      = 'https://titovcode.com'
defaultContentLanguage = 'ru'
title        = 'Dmitry Titov'
theme        = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true
enableEmoji = true

[author]
  name = "Dmitry Titov"

[params]
  homeSubtitle = "Backend developer"
  enableSharingButtons = true

  EnableGlobalLanguageMenu = true
  enableThemeToggle = false

[params.portrait]
  path = "/assets/avatar.png"
  alt = "It's me"


[params.logo]
  logoMark = "["
  logoText = "titovcode.com ]$"

[params.footer]
    trademark = true
    rss = false
    copyright = false
    author = true

    topText = []
    bottomText = []

[[params.social]]
  name = "github"
  url = "https://github.com/korableg/"

[[params.social]]
  name = "email"
  url = "mailto:dim@titovcode.com"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/dmitry-titov-94276459/"

[[params.social]]
  name = "telegram"
  url = "https://t.me/korableg"

[[params.social]]
  name = "hackerrank"
  url = "https://www.hackerrank.com/titov_de/"

[languages]

  [languages.en]
    title = "Dmitry Titov"
    homeSubtitle = "Backend developer"
    weight = 1
    # [[languages.en.menu.main]]
    #   identifier = "posts"
    #   name       = "Posts"
    #   url        = "posts/"
    [[languages.en.menu.main]]
      identifier = "about"
      name       = "About"
      url        = "/about"
    [[languages.en.menu.main]]
      identifier = "links"
      name       = "Useful links"
      url        = "/links"
    
  [languages.ru]
    title = "Дмитрий Титов"
    homeSubtitle = "Backend developer"
    weight = 2
    # [[languages.ru.menu.main]]
    #   identifier = "posts"
    #   name       = "Статьи"
    #   url        = "posts/"
    [[languages.ru.menu.main]]
      identifier = "about"
      name       = "Обо мне"
      url        = "/about"
    [[languages.ru.menu.main]]
      identifier = "links"
      name       = "Полезные ссылки"
      url        = "/links"